import { useState } from 'react'
import { Badge, Empty } from './shared.jsx'

/**
 * Unilog's own labelled delivery rows, scored against what the engine produces.
 *
 * Two states are always shown together. Quoting the first alone — the formatter
 * given the attribute values — reads as an end-to-end claim the pipeline cannot
 * support, and overstating a result is the one thing this engine is built not
 * to do. The distance between the two columns is the sourcing gap, and it is
 * the most useful thing on this screen.
 */
export default function GroundTruthPanel({ data, loading }) {
  if (loading) {
    return (
      <div className="card">
        <div className="card-body" style={{ textAlign: 'center', padding: 28 }}>
          <span className="spinner" /> Scoring against the labelled rows…
        </div>
      </div>
    )
  }
  if (!data) return null

  const s = data.summary

  return (
    <>
      <div className="card">
        <div className="card-head">
          <h3>Accuracy against their ground truth</h3>
          <div className="spacer" />
          <span className="pill">{s.rows} labelled rows</span>
          <span className="pill">{s.fields_scored} fields</span>
        </div>
        <div className="card-body">
          <div className="gate-intro" style={{ marginBottom: 12 }}>
            Unilog supplied two fully worked delivery rows. Every prose field below
            is generated by formula against their character limits — never free
            text — and compared with their value character for character.
          </div>

          <div className="summary-grid">
            <div className="stat">
              <div className="stat-value" style={{ color: 'var(--ok)' }}>
                {s.exact_given_attributes}/{s.fields_scored}
              </div>
              <div className="stat-label">
                exact when the attribute<br />values are supplied
              </div>
            </div>
            <div className="stat">
              <div className="stat-value" style={{ color: 'var(--warning)' }}>
                {s.exact_from_input_row}/{s.fields_scored}
              </div>
              <div className="stat-label">
                exact from the 6-column<br />input row alone
              </div>
            </div>
          </div>

          <div className="banner banner-warn" style={{ marginTop: 12 }}>
            The difference is not a formatting failure. Series, Mounting, Wash
            Cycles and Voltage are not in a catalogue row — they are on the
            manufacturer's site, which their own row cites as <em>MFR URL</em>.
            The copy engine is exact; the sourcing is the open problem.
          </div>
        </div>
      </div>

      {data.cases.map((c) => <GroundTruthCase key={c.mpn} item={c} />)}
    </>
  )
}

function GroundTruthCase({ item }) {
  const [showOurs, setShowOurs] = useState(false)
  const exact = item.fields.filter((f) => f.match_given).length

  return (
    <div className="card">
      <div className="card-head">
        <h3>{item.mpn}</h3>
        <div className="spacer" />
        <Badge kind={exact === item.fields.length ? 'prov-supplied' : 'sev-error'}>
          {exact}/{item.fields.length} exact
        </Badge>
        <button
          type="button"
          className="btn btn-sm"
          style={{ padding: '1px 8px' }}
          onClick={() => setShowOurs((v) => !v)}
        >
          {showOurs ? 'hide ours' : 'show ours'}
        </button>
      </div>

      <div className="card-body tight">
        <div className="gate-reason" style={{ marginBottom: 10 }}>
          {item.brand} · {item.classpath || 'unclassified'}
          <br />
          <span className="mono">{item.part_desc}</span>
        </div>

        {item.fields.map((f) => (
          <div className="gate-row" key={f.column}>
            <div className="gate-row-head">
              <Badge kind={f.match_given ? 'prov-supplied' : 'sev-error'}>
                {f.match_given ? 'identical' : 'differs'}
              </Badge>
              <span className="gate-attr">{f.column}</span>
              <span className="pill">{f.rule}</span>
              {f.expected_length > 0 && (
                <span className="pill">{f.expected_length} chars</span>
              )}
            </div>

            <div className="content-block" style={{ marginTop: 6 }}>
              <div className="content-label">Unilog expected</div>
              <div className="content-text">{f.expected || <em>(blank)</em>}</div>
            </div>

            {showOurs && (
              <div className="content-block" style={{ marginTop: 6 }}>
                <div className="content-label">
                  Ours, given the attribute values
                </div>
                <div
                  className="content-text"
                  style={{ color: f.match_given ? 'var(--ok)' : 'var(--error)' }}
                >
                  {f.given_attributes || <em>(empty)</em>}
                </div>
              </div>
            )}

            <div className="gate-reason" style={{ marginTop: 5 }}>
              From the input row alone:{' '}
              <span style={{ color: f.match_from_input ? 'var(--ok)' : 'var(--warning)' }}>
                {f.from_input_row || '(empty — the values are not in the row)'}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export function GroundTruthEmpty() {
  return (
    <div className="card">
      <Empty icon="◨" title="Scoring against the labelled rows">
        Unilog's two fully worked delivery rows are the only ground truth there is.
        This screen puts their value next to ours for every prose field, and shows
        both what the formatter achieves given the attribute values and what the
        pipeline reaches from a six-column catalogue row.
      </Empty>
    </div>
  )
}
